### ISSUE TITLE
Differences with `nplusone`?

### ISSUE THREAD

**Issue by sobolevn** [taobojlen/django-zeal#10]
Hi! Thanks for building this tool, it sounds very useful.

Docs do not specify why this tool was created: what are the main differences with `nplusone`?
Thanks again!

**Comment by taobojlen** [comment]
hi @sobolevn, great question! i just added a small section with the main differences to the README: https://github.com/taobojlen/zealot?tab=readme-ov-file#comparison-to-nplusone

out of curiosity, how did you hear about zealot?

**Comment by sobolevn** [comment]
You are featured on https://django-news.com :)
