### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by serl** [taobojlen/django-zeal#24]
We have a big project with lots of tests (~5000), note that an important part of them are good old unit tests, and don't touch the HTTP stack. The whole suite takes ~5 minutes (of course we have `pytest-xdist` and stuff).

I enabled django-zeal only with the middleware, and now the test suite takes about twice the time: ~10 minutes (and finds a bunch of violations, but that's definitely _my_ problem).

Let me know if you have any suggestion on how I can help to improve the situation, and/or if you know already about some low-hanging improvements I can try to make.

**Comment by taobojlen** [comment]
Thanks for the report @serl ! I just released django-zeal 1.4.1 which includes a performance fix -- hopefully your test suite should go back to taking ~5 minutes once you update. Let me know how it goes!
